
services:
  frontend:
    image: yourusername/time-capsule-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  backend:
    image: yourusername/time-capsule-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"  # Avoid port 3000 conflict
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge